name: Elso workflow

on: #mikor legyen a worflow vegrehajtva
  push

jobs:
  build_and_test: #neve a jobnak
    runs-on: ubuntu-latest #milyen virtual kornyezetben futtassuk
    steps: #lista a vegrehajtando lepesekrol
      - uses: actions/checkout@v2 #szedje le a kodot gitrol
      - name: Build the application
      - run: g++ -Wall main.cpp -o gcd #forditsa le a kodot
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: gcd
      - name: Run input-output tests
      - run: ./run_test.sh gcd generated_output.txt
      - name: Check result of input-output tests
      - run: diff generated_output.txt good_output.txt
      - name: Upload generated output
        uses: actions/upload-artifact@v2
        with:
          name: generated_output
          path: generated_output.txt