name: Elso workflow

on: #mikor legyen a worflow vegrehajtva
  push

jobs:
  build: #neve a jobnak
    runs-on: ubuntu-latest #milyen virtual kornyezetben futtassuk
    steps: #lista a vegrehajtando lepesekrol
      - uses: actions/checkout@v2 #szedje le a kodot gitrol
      - run: g++ -Wall main.cpp #forditsa le a kodot
      - run: IFS=$'\n'; for i in `cat input.txt`; do echo "Szamok: $i, lko:"; echo "$i" | ./a.out ; done